name: matsci465
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # notebooks
  - jupyterlab
  - ipykernel
  - ipywidgets
  - ipympl

  # core scientific stack
  - numpy
  - scipy
  - matplotlib

  # microscopy / 4D-STEM stack
  - hyperspy=2.2
  - hyperspy-gui-ipywidgets
  - hyperspy-gui-traitsui
  - py4dstem=0.14
  - ncempy
  - h5py
  - hdf5plugin
  - scikit-image
  - imageio
  - pooch

  # utilities often used by the above
  - dask
  - distributed
  - tqdm
  - pint